### PR TITLE
[Mellanox] Change mellanox buffer migrator for new SKU Mellanox-SN2700-D40C8S8

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- What I did**

Change mellanox buffer migrator for new SKU Mellanox-SN2700-D40C8S8

**- How I did it**

New SKU Mellanox-SN2700-D40C8S8 will reuse buffer configuration of Mellanox-SN2700-D48C8

**- How to verify it**

Run sonic-mgmt qos test and pass

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by stephenxs** [comment]
Let's add the unit tests for the new SKUs.

**Comment by Junchao-Mellanox** [comment]
sure

**Comment by Junchao-Mellanox** [comment]
@stephenxs  uni test added. pls review again. thanks!

**Review by stephenxs — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
https://github.com/Azure/sonic-utilities/pull/1470

**Pull request closed without merging**
